codecov:
  require_ci_to_pass: yes
  max_report_age: off  # Disable max age check to prevent upload rejections
  notify:
    after_n_builds: 1  # Only Python 3.11 uploads coverage

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 30%
        threshold: 1%
        if_ci_failed: error
    
    patch:
      default:
        target: 30%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/"
  - "notebooks/"
  - "scripts/"
  - "**/__pycache__"
  - "**/*.pyc"
